### ISSUE TITLE
Demo video doesn't work :)

### ISSUE THREAD

**Issue by cristalix** [Athlon1600/youtube-downloader#1]
Hi, congrats to your fist issue.

Demo video doesn't work https://www.youtube.com/watch?v=QxsmWxxouIM. I cannot open grabbed links.

More about encrypted signatures

https://www.quora.com/How-can-I-make-a-YouTube-video-downloader-web-application-from-scratch

**Comment by Athlon1600** [comment]
Not possible. Here is a live version of that script hosted on my server:  
https://api.unblockvideos.com/youtube_downloader?id=https://www.youtube.com/watch?v=QxsmWxxouIM  
  
and as you can see links are parsed correctly. Are you getting FALSE from getDownloadLinks method or are you getting links that are not working?

**Comment by cristalix** [comment]
Pretty possible, I found the bug. When you download a video in Europe, this regex will not match in current version:

`if(preg_match('@<script\s*src="([^"]+player-en_US[^"]+)@', $html, $matches)){`

because you will have something such as `player-fr_FR` or `player-de_DE` so either change regex or add additional parameters to downloaded Youtube HTML page:

`$html = $this->curl("https://www.youtube.com/watch?v={$video_id}&ps=default&eurl=&gl=US&hl=en");`

Then it works.

**Comment by Athlon1600** [comment]
That part was actually fixed back in January 5:  
https://github.com/Athlon1600/youtube-downloader/commit/8ed5c19299fad29f6da4f781ae627e669316f4f8 
  
are you using the latest version of youtube-downloader?

**Comment by cristalix** [comment]
Aparently I'm not using the latest version. I downloaded script using composer and after command

`php composer.phar update`

I get `nothing to install or update` message. This is my composer file: 

```
{
    "require": {
        "athlon1600/youtube-downloader": "^1.0"
    }
}
```

I'm new to composer (2nd time used). Is error on my side?

**Comment by Athlon1600** [comment]
yeah that's because php-proxy-app is asking for youtube-download version 1.0. That fix I made is on the dev-master branch that hasn't been "versioned" yet. Try changing that line into:  
```json
        "athlon1600/youtube-downloader": "dev-master"
```

but that will probably give you an error. I still have to make a few changes to it so 1.1 version is not yet available but once it is, I'll just start requiring php-proxy-app for 1.1 instead of 1.0. I'll look into all this over the weekend.

**Comment by cristalix** [comment]
Great, it works now, thank you.
