### ISSUE TITLE
encrypted videos are not playing. Please solved this bug asap.

### ISSUE THREAD

**Issue by guddumodok** [Athlon1600/youtube-downloader#100]

**Comment by ninacoder-info** [comment]
same here, any news?

**Comment by Athlon1600** [comment]
any video in particular that I could test as an example? Few videos that I've tried through:
https://youtube-downloader-jan16.herokuapp.com/

have worked

**Comment by ninacoder-info** [comment]
Yes that strange, your demo still working but the source code no longer working

**Comment by ninacoder-info** [comment]
@Athlon1600 seen like it is back to working now, strange
