### ISSUE TITLE
All in one

### ISSUE THREAD

**Issue by kihanb** [Athlon1600/youtube-downloader#104]
thanks for your helpful library, but I can't install it with Composer in my sharing host! so I was wondering that how I can convert it to one file library and use it with just a require or include command?

**Comment by Athlon1600** [comment]
You can do it by installing via composer on your own computer first, and then moving all those files to your shared hosting.

Run `composer require athlon1600/youtube-downloader "^3.0"` in any directory on your computer. This will create a `vendor` folder with `autoload.php` file in it. Now whenever you need to use youtube download library, you just need to include that one autoload file like this:

```php
require("vendor/autoload.php");

use YouTube\YouTubeDownloader;

$download = new YouTubeDownloader();
```

this works
