### ISSUE TITLE
getdownloadlinks method issue

### ISSUE THREAD

**Issue by sareban101** [Athlon1600/youtube-downloader#105]
It unable to find links for videos released more than two years ago

please fix it

thank you for your lib 🌺

**Comment by AgentSmith0** [comment]
Probably a duplicate of #109. Please leave a comment there.

**Comment by Athlon1600** [comment]
Need to know which videos specifically can't be downloaded, but since this issue is already months old, it has probably since been fixed already. Try using latest release.
