### ISSUE TITLE
It is not working anymore

### ISSUE THREAD

**Issue by MikeTester21** [Athlon1600/youtube-downloader#110]
Hello, love this but there seems to be big problem. It seems youtube removed the http://www.youtube.com/get_video_info access for everyone so it is not working anymore? Did the url change? Do you know the new url?

**Comment by MikeTester21** [comment]
update: 

I have updated the code in YouTubeDownloader.php file and added : html5=1&

so it looks : https://www.youtube.com/get_video_info?html5=1&....

and it seems to work for now? Let me know if this was the only problem or if I am missing something.

**Comment by dam024** [comment]
Hi, thanks for modifications, it's working on my side. Unfortunately, you just forgot to commit changes... so I changed directly on my copy, it's just to inform you.

**Comment by Athlon1600** [comment]
Yup it seems like YouTube wants to retire that endpoint already, but adding html=1 for now still makes it work.  I've made the changes to the code, so just do composer update from your end and this should work now.

https://github.com/Athlon1600/youtube-downloader/releases/tag/v3.0.1
