### ISSUE TITLE
Support for other sites

### ISSUE THREAD

**Issue by Mewgood** [Athlon1600/youtube-downloader#111]
Is this planned? Kind of limited that it only supports YouTube.

**Comment by AgentSmith0** [comment]
I don't think it is a good idea to support all video sharing services in one library, which would also be quite much work to keep them all updated. It would be better to create multiple libraries that work standalone and maybe then creating a library that parses the link and selects the right library.

**Comment by Athlon1600** [comment]
^ would have to agree with that. It would be too much work. There are plans in the works though on adding more features to this library like the ability to bypass age restrictions, extract youtube comments, fetch related videos, etc... but the point is that all of that would deal with youtube.com exclusively.
