### ISSUE TITLE
Some videos do not return links

### ISSUE THREAD

**Issue by AgentSmith0** [Athlon1600/youtube-downloader#113]
Try here: https://youtube-downloader-v3.herokuapp.com/
With this video: https://www.youtube.com/watch?v=QonEs-Teci4
The most other videos are working, only older ones are not always working.
This issue is probably a duplicate of #109.

**Comment by AgentSmith0** [comment]
Closed, because duplicate of #109

**Comment by Athlon1600** [comment]
duplicate of #109
