### ISSUE TITLE
why does the downloader only return one video link?

### ISSUE THREAD

**Issue by shreejalmaharjan-27** [Athlon1600/youtube-downloader#118]

**Comment by Athlon1600** [comment]
which method are you using? `getAllFormats` or `getFirstCombinedFormat`? And for which video is this for?

**Comment by shreejalmaharjan-27** [comment]
this is for any video i try on. I have not changed any code.

> which method are you using? `getAllFormats` or `getFirstCombinedFormat`? And for which video is this for?
