### ISSUE TITLE
New changes in Youtube's get_video_info

### ISSUE THREAD

**Issue by dam024** [Athlon1600/youtube-downloader#119]
Hi, 

I'm letting you know that there was new changes in the Youtube's get_video_info file. The API responses now with 404 http's error when requesting with your current parameters. I have found a solution, which works for now (but no idea for how long... The API seems to change all the time...). 
On file YoutubeDownloader.php, just change parameters of the query, around lines 50 to 60 with those parameters : 

` ['html5' => 1,
                'video_id' => $video_id,
                'eurl' => 'https%3A%2F%2Fyoutube.googleapis.com%2Fv%2Fonz2k4zoLjQ',
                'c' => 'TVHTML5',
                'cver' => '6.20180913',
                'el' => 'embedded' // or detailpage. default: embedded, will fail if video is not embeddable
]`

For more infos, I found this solution there : https://stackoverflow.com/questions/67615278/get-video-info-youtube-endpoint-suddenly-returning-404-not-found/67629882

**Comment by DanielSpravtsev** [comment]
Can confirm that, current 3.0.1 version work local with "Valet" server on Mac os, but don't work on Production at Ubuntu without @dam024 changes.
Ping @Athlon1600

**Comment by Athlon1600** [comment]
sorry, haven't had time to check up on this project lately... your solution works. The original youtube-dl solves it the same way too: https://github.com/ytdl-org/youtube-dl/blob/47f2f2fbe9730b041b91451d17279216f311ffc2/youtube_dl/extractor/youtube.py#L1507

Thanks to @terrylaire for creating a pull request. I will push this into a new release as soon as possible.
