### ISSUE TITLE
How to install without Composer

### ISSUE THREAD

**Issue by ndsda** [Athlon1600/youtube-downloader#123]
I copied the src directory, but when I run it I get this error: 

`Fatal error: Uncaught Error: Class 'Curl\BrowserClient' not found in /Browser.php:8`

Where can I get Curl\BrowserClient?

**Comment by ndsda** [comment]
How do I get all the dependencies?

**Comment by AgentSmith0** [comment]
Have a look at this issue: https://github.com/Athlon1600/youtube-downloader/issues/112#issuecomment-854085132
You can download the zip file and include the autoload.php file. Alternatively you can go to https://php-download.com/package/athlon1600/youtube-downloader and download the zip file there, but they are now a paid service. I hope this helps.

**Comment by peter279k** [comment]
You can also check my [new repository](https://github.com/peter279k/youtube-downloader-standalone) to resolve this issue.

I use the [clue/phar-composer](https://github.com/clue/phar-composer) to build current released Phar with different PHP versions and released tag.

You can follow the [usage](https://github.com/peter279k/youtube-downloader-standalone#usage) to download use the Phar file :).

**Comment by Athlon1600** [comment]
^ that works. I've also added back the complete pre-installed version of youtube-downloader as a zip file here:
https://github.com/Athlon1600/youtube-downloader/releases/tag/v3.0.2

so you have two options now. I might start just including .phar file with each new release, because that's a much better idea.

**Comment by ndsda** [comment]
@Athlon1600 Thanks for the zip file with the version that doesn't use composer.
