### ISSUE TITLE
getPage not working! | Before you continue to YouTube

### ISSUE THREAD

**Issue by northvector** [Athlon1600/youtube-downloader#125]
getPage method not works because of this 
![image](https://user-images.githubusercontent.com/22070926/124930422-8fb77780-e016-11eb-8a45-24f2710b25f4.png)

**Comment by northvector** [comment]
Fixed for now, just add CONSENT cookie with this value: `YES+cb.20210706-13-p0.en+FX+018`
or add this line to Client.php  (php-curl-client) line 58
 `curl_setopt($ch, CURLOPT_HTTPHEADER, array("Cookie: CONSENT=YES+cb.20210706-13-p0.en+FX+018"));`

**Comment by Athlon1600** [comment]
^ an alternative to that would be to call the new `consentCookies` method:  
https://github.com/Athlon1600/youtube-downloader/blob/master/src/Browser.php#L52

that will set the proper cookies to your web-browser and you will never see that cookies message again.
