### ISSUE TITLE
No Youtube Video name?

### ISSUE THREAD

**Issue by TendiF** [Athlon1600/youtube-downloader#13]
how to get youtube original title?

SOLVE WITH EXISTING FUNCTION

```
        require_once(plugin_dir_path(__FILE__).'vendor/autoload.php');
        $yt             = new YouTubeDownloader();
        $links          = $yt->getDownloadLinks($_POST['youtubeLink']);
        $youtube_id     = $yt->extractId($_POST['youtubeLink']);
        $restriction    = $yt->curl('https://api.unblockvideos.com/youtube_restrictions?id='.$youtube_id);
        var_dump(json_decode($restriction)[0]->title);exit;
```

**Comment by TendiF** [comment]
require_once(plugin_dir_path(__FILE__).'vendor/autoload.php');
        $yt             = new YouTubeDownloader();
        $links          = $yt->getDownloadLinks($_POST['youtubeLink']);
        $youtube_id     = $yt->extractId($_POST['youtubeLink']);
        $restriction    = $yt->curl('https://api.unblockvideos.com/youtube_restrictions?id='.$youtube_id);

**Comment by mesbahulalam** [comment]
I believe the same service is provided by YouTube with more info here.
`https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v='.$youtube_id.'&format=json`
