### ISSUE TITLE
"Something went wrong: "

### ISSUE THREAD

**Issue by ndsda** [Athlon1600/youtube-downloader#130]
I'm running the basic script as shown in the docs under the heading "Usage". But it returns, "Something went wrong: " as an exception with no details about what went wrong. 

It was working fine yesterday. I tried it with 3 videos and it returned the download links for video and audio.

How do I find out what went wrong?

**Comment by AgentSmith0** [comment]
I had the same problem, maybe you get redirected to the youtube consent page. You must call `$youtube->getBrowser()->consentCookies();` first. Have a look at this: https://github.com/Athlon1600/youtube-downloader/issues/125
I hope this will solve your issue.

**Comment by ndsda** [comment]
Oh wow, yes that solved the problem. Thanks for your help!
