### ISSUE TITLE
How to specify the IP address to use

### ISSUE THREAD

**Issue by ndsda** [Athlon1600/youtube-downloader#134]
Is there an easy way to specifiy the IP address to use for requests?

My server has 8 IPs and it would be useful to be able to use all of them to avoid the 'Too many requests' problem.

If this functionality doesn't exist, perhaps it could be considered for inclusion in future versions (if it isn't already been!)

**Comment by Athlon1600** [comment]
it's there already, and I use it myself all the time.

![image](https://user-images.githubusercontent.com/1063088/126709706-d5a37300-25e0-47d9-8e2c-d690759fe5b6.png)

You might also want to use a separate cookies file and a different user-agent for each of those IPs so as to appear entirely unique to YouTube

**Comment by ndsda** [comment]
Is there a way for me to set the IP address with the CURLOPT_INTERFACE option?

Thanks for your advice about user-agents and cookie files.

**Comment by Athlon1600** [comment]
> Is there a way for me to set the IP address with the CURLOPT_INTERFACE option?
> 
> Thanks for your advice about user-agents and cookie files.

For that, you could just modify `Browser.php` file:  
https://github.com/Athlon1600/youtube-downloader/blob/master/src/Browser.php

and add something like:
```php
    public function usingCustomIP($ip)
    {
        $this->options[CURLOPT_INTERFACE] = $ip;
        return $this;
    }
```

and then use it:
```php
$youtube = new YouTubeDownloader();
$youtube->getBrowser()->usingCustomIP("YOUR_IP_GOES_HERE");
```
