### ISSUE TITLE
mp3 is not shareable

### ISSUE THREAD

**Issue by tehreemafarooq** [Athlon1600/youtube-downloader#136]
mp3 is not shareable of youtube  due to mp4a codex how to convert it into mp3 codex and 1080p with sound

**Comment by 89z** [comment]
Whats wrong with mp4a?

**Comment by tehreemafarooq** [comment]
it is not shareable i checked  in adobe premier and whatsapp share

**Comment by 89z** [comment]
did you try `.m4a`?

**Comment by tehreemafarooq** [comment]
yup i did and please help me to merge audio and video of youtube  dash
videos

**Comment by tehreemafarooq** [comment]
thanks i used api for converting to mp3

**Comment by tehreemafarooq** [comment]
i tried .mp4a it was not shareable due to mp4a codec we need to convert it
into mp3 codecc
