### ISSUE TITLE
Signature Decoder broken. Error 403

### ISSUE THREAD

**Issue by rustynail1984** [Athlon1600/youtube-downloader#138]
Encrypted Videos cant be downloaded since yesterday, got Error 403, so Signature Decoder is broken.

Example Video: https://www.youtube.com/watch?v=lWA2pjMjpBs

**Comment by jiaghara** [comment]
Replace this code on SignatureDecoder.php

New code

` } else if (preg_match('@(?:\b|[^a-zA-Z0-9$])([a-zA-Z0-9$]{2,3})\s*=\s*function\(\s*a\s*\)\s*{\s*a\s*=\s*a\.split\(\s*""\s*\)@is', $js_code, $matches)) {`

old code

` } else if (preg_match('@(?:\b|[^a-zA-Z0-9$])([a-zA-Z0-9$]{2})\s*=\s*function\(\s*a\s*\)\s*{\s*a\s*=\s*a\.split\(\s*""\s*\)@is', $js_code, $matches)) {`

**Comment by Athlon1600** [comment]
I can't replicate this issue on my end, but I can assume that this tiny change would not break any existing logic, so let's just go ahead with it
https://github.com/Athlon1600/youtube-downloader/commit/f739192fcfe63c2aeefaf7a8584cc98f62b58492

**Comment by kclauhk** [comment]
Can you get a valid link for these videos?
https://www.youtube.com/watch?v=cOlhzKPX0KU
https://www.youtube.com/watch?v=ldBroBrV6Fg

All download links give me 403 error... and some other videos have the same error.
https://youtube-downloader-v3.herokuapp.com also does not work with these videos (403).
I checked that both the new & old code can parse the function named JB:
(
    [0] => JB=function(b){g.Ab(a,function(c){c(b)}
    [1] => g.Ab(a,function(c){c(b)
)
don't know what is the problem.

**Comment by jiaghara** [comment]
yes, it happen because same function name coming 2 time from youtube, you can fix it replace code with new in SignatureDecoder.php

New code
` if (preg_match('/' . $func_name . '=function\([a-z]+\){(.*?)}/', $player_html, $matches)) {`

Old code:

` if (preg_match('/' . $func_name . '=function\(\s*a\s*\){(.*?)}/', $player_html, $matches)) {`

let me know is working or not

**Comment by Kryd0s** [comment]
> yes, it happen because same function name coming 2 time from youtube, you can fix it replace code with new in SignatureDecoder.php
> 
> Old code:
> ` if (preg_match('/' . $func_name . '=function\([a-z]+\){(.*?)}/', $player_html, $matches)) {`
> 
> New code:
> ` if (preg_match('/' . $func_name . '=function\(\s*a\s*\){(.*?)}/', $player_html, $matches)) {`
> 
> let me know is working or not

I'm getting 403 on all links, and this change did not fix it for me.

**Comment by jiaghara** [comment]
> I'm getting 403 on all links, and this change did not fix it for me.

paste any vevo videos direct link here 

i want to know your signature is decoding or not and then we will fix your issue

**Comment by Kryd0s** [comment]
I'm so sorry. I don't check github very often. I just upgraded from v3.0.2 to v3.1.0 and it's generating links correctly now.
