### ISSUE TITLE
Multiple videos can't downloading...

### ISSUE THREAD

**Issue by jilaan** [Athlon1600/youtube-downloader#141]
if i am start download video 1 is working fine if I start 2 3 videos then not downloading how can I do this functions to download multiple videos ?

thanks

**Comment by jiaghara** [comment]
this function is working very well for multi download in same time.

what error you get when you go for multi download, can you explain more detail.

**Comment by jilaan** [comment]
thanks for reply,

i am using shared hosting may be this issue for shared hosting if I download one by one then is working perfect kindly suggest me vps?

thanks

**Comment by jiaghara** [comment]
vps provider can't allow mp3 converter but you can directly download videos and audio files,

**Comment by jilaan** [comment]
ok sir thanks
