### ISSUE TITLE
What are the requirements for my server to run this files

### ISSUE THREAD

**Issue by linbooks** [Athlon1600/youtube-downloader#144]
I am a pretty much rookie, so can you tell me what are the requirements should I install in my server

**Comment by Athlon1600** [comment]
> I am a pretty much rookie, so can you tell me what are the requirements should I install in my server

Both the requirements and the steps for installing it, are all inside the readme. As long as you have a reasonable version of PHP installed on your server with a few extensions, you should be all good

![](https://camo.githubusercontent.com/339ed31a6008c464a12a250a405c05d160898686bfd7db4e14dc344c3ed5f98d/68747470733a2f2f692e696d6775722e636f6d2f33394c494530722e706e67)
