### ISSUE TITLE
[Request] API endpoint

### ISSUE THREAD

**Issue by GokulNC** [Athlon1600/youtube-downloader#153]
Thanks for this great work!

I have a request:

Is it possible to expose an public endpoint (with **CORS enabled**), like this:
https://unblockvideos.com/video_info.php?url=https://www.youtube.com/watch?v=BaW_jenozKc

which will return the best video download link.

Or is there something already like this? (if so, please mention in the README)

**Comment by Athlon1600** [comment]
Yes, something like that is in the works, but still a long way to go. It's a separate project from this though, but once it goes live, I will definitely put a link to it in the README
