### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by JamieSlome** [Athlon1600/youtube-downloader#156]
Hey there!

I belong to an open source security research community, and a member (@rudloff) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by Athlon1600** [comment]
Done

https://github.com/Athlon1600/youtube-downloader/blob/master/SECURITY.md

**Comment by JamieSlome** [comment]
Great, we sent you an e-mail! 👍 

You can also view the report directly here:

https://huntr.dev/bounties/e6f2d10e-be4d-4d0d-9068-fc7a6dc0e2fc/
