### ISSUE TITLE
Run locally

### ISSUE THREAD

**Issue by Karimeamine** [Athlon1600/youtube-downloader#171]
update the line require('../vendor/autoload.php');

to require('../../../../vendor/autoload.php');
in stream.php and video_info.php
then run the command 
php -S localhost:8000 -t vendor/athlon1600/youtube-downloader/public

**Comment by peter279k** [comment]
I think you can create the PR for the issue :).

**Comment by Athlon1600** [comment]
I think it's the instructions in the readme that are wrong. FIXED https://github.com/Athlon1600/youtube-downloader/commit/f214319026435c4c571128464a8d8404f9b3353d
