### ISSUE TITLE
videos opening not downloading

### ISSUE THREAD

**Issue by danieldanie** [Athlon1600/youtube-downloader#18]
hello

when i click on download video button videos opening not downloading

**Comment by mesbahulalam** [comment]
That is because YouTube is not sending the headers that makes the browser see the file as a downloading material. You can either use your server as a proxy and change the headers or right click on the download link and choose save as...

**Comment by Athlon1600** [comment]
^ he's right. You would need something like this:  
https://stackoverflow.com/questions/7263923/how-to-force-file-download-with-php  
  
But it might not be a bad idea to include this functionality within youtube-downloader. Something as simple as:  
```php
$yt->download('youtube_video');
```  
  
Will keep this in mind.
