### ISSUE TITLE
Missing Formats

### ISSUE THREAD

**Issue by RichieMcMullen** [Athlon1600/youtube-downloader#19]
Video formats (1080, 4K, etc...) above 720p are not available for some reason.

**Comment by andraantariksa** [comment]
Got the same problem

**Comment by Athlon1600** [comment]
> Video formats (1080, 4K, etc...) above 720p are not available for some reason.

The script does not do any "deep searching" to find such video formats. It just picks up whatever videos can be found on that initial video page. And that is what keeps youtube-downloader so fast. But yes, there should probably be an option to request ALL video formats available for that video. That's on my to-do list now.
