### ISSUE TITLE
Video links work on localhost, doesn't work on server

### ISSUE THREAD

**Issue by cristalix** [Athlon1600/youtube-downloader#2]
Hi,
just tested the script and links for this video work on localhost and dcannot be opened when script runs from remote server https://www.youtube.com/watch?v=GWKtoSza8lM

**Comment by Athlon1600** [comment]
So the mp4 links returned by the script from from your localhost but not from your home computer?

**Comment by cristalix** [comment]
Yes, this is another example https://www.youtube.com/watch?v=odfnQBSbaAc Video can be opened (downloaded) only from same machine as it was requested. Now I try to find if is it country/user-agent/IP address/cookies specific.

**Comment by cristalix** [comment]
It's a Google's CDN issue.
