### ISSUE TITLE
Help :(

### ISSUE THREAD

**Issue by p4196** [Athlon1600/youtube-downloader#21]
Hi,
I love this youtube-downloader, but I'm not able to make it work like https://api.unblockvideos.com/youtube_downloader
Can you help?
Thank You :D

**Comment by Athlon1600** [comment]
It should. The source code for that API endpoint is just this:  
```php

$youtube = new \YouTubeDownloader();
$links = $youtube->getDownloadLinks($id);
echo json_encode($links);
```

is it at least returning some links?

**Comment by p4196** [comment]
Hi,
Thanks for your reply
Yes, it is returning the links, but the issue is that all the links are using the server IP
and the &redirect=true is not working.
What I need is only to retrieve 1 .mp4 link
api.unblockvideos.com is working, when I click a link it goes directly to the source
In my case is not working
1=> error 403 when I click a link
2=> &redirect=true is not working
Thanks again for your time and help :D
Have a great weekend

**Comment by p4196** [comment]
Any update?

**Comment by mrqaidi** [comment]
i have  same issue   nay update on that ?

**Comment by p4196** [comment]
Hi,
Thanks for your help
Now the url is working, but I can't get a video based on ?id=
----------------------------Is not working------------------------------|
$youtube = new \YouTubeDownloader();                                          |
$links = $youtube->getDownloadLinks($id);                                    |=> output false
echo json_encode($links);                                                                 |
------------------------------------------------------------------------|
------------------Is working only with a single video-------------
$yt = new YouTubeDownloader();
$links = $yt->getDownloadLinks("https://www.youtube.com/watch?v=QxsmWxxouIM");
---------------------------------------------------------------------------
Thanks again for your help
Have a great day

**Comment by Shareiv** [comment]
**a question how can I do to have the array -> itag 140, 249, 251 if you can help me**

**Comment by hex-firebone** [comment]
Hello guys,

why don't you guys try this library

https://github.com/hex-firebone/YouTube-Downloader

**Comment by pramir** [comment]
Hi. Is there a way to download subtitles of the video with this function ?

**Comment by Athlon1600** [comment]
nope. Not at the moment. youtube-dl can do this though:  
https://github.com/rg3/youtube-dl
