### ISSUE TITLE
Error 403 - Forbidden

### ISSUE THREAD

**Issue by stefankuehnel** [Athlon1600/youtube-downloader#23]
The Demo API and the code are working but when I try to access the video ressources given, googlevideo.com responds with either a 403 Forbidden Error or a blank page.

I tried to access the ressource with Chrome, Firefox and a different IP with the Tor Browser. 

All test weren't successful. Maybe YouTube changed something in their code. When I access the Demo Stream Version it redirects me to redirector.googlevideo.com instead of https://---.googlevideo.com/videoplayback?...

**Comment by Ahmed18** [comment]
i have the same issue

**Comment by harisnaeemofficial** [comment]
Same Issue please resolve it . the same issue was facing youtube-dl but in the latest update the issue is resolved . there is new extraction method for youtube video signature which is causing the problem .

**Comment by scrapewww** [comment]
also getting 403 error when actually trying to download provided urls..

**Comment by stuthemoo** [comment]
I'm also seeing the 403 error for all video URLs.

**Comment by madcode-git** [comment]
Use this one https://github.com/madcode-git/YouTube-Downloader

**Comment by Athlon1600** [comment]
Fix has been made and links in the demo section are now working:  
https://github.com/Athlon1600/youtube-downloader/commit/a2c1e1c6165d85573db701705fe490ffe79852f6
