### ISSUE TITLE
Cannot download some videos

### ISSUE THREAD

**Issue by sodevrom** [Athlon1600/youtube-downloader#26]
Hey!
 Any chance you can update the script with latest YT changes?
 For example the video with this id: 3KiRiNyWVV4
 Cannot be downloaded.

 Thanks

**Comment by madcode-git** [comment]
You may try this one https://github.com/madcode-git/YouTube-Downloader

**Comment by Athlon1600** [comment]
^ That thing above does not work and is just pretending to be something original. Why not just fork this project instead?   
  
Update has been made: it should all be working now. 
https://github.com/Athlon1600/youtube-downloader/commit/a2c1e1c6165d85573db701705fe490ffe79852f6
