### ISSUE TITLE
Undefined variable $result 

### ISSUE THREAD

**Issue by DevinNorgarb** [Athlon1600/youtube-downloader#28]
![screenshot from 2018-12-30 09-53-10](https://user-images.githubusercontent.com/12491966/50545346-2bcbc100-0c19-11e9-8ae6-934fdbeb3a02.png)

The third Demo link (`Works with Age-Restricted videos too:`) in the Readme throws this error:
`Undefined variable: result in YouTubeDownloader.php line 443`

This link:
[https://api.unblockvideos.com/youtube_downloader?id=dUiuuoCAMuw&selector=mp4&redirect=true
](https://api.unblockvideos.com/youtube_downloader?id=dUiuuoCAMuw&selector=mp4&redirect=true
)

**Comment by Athlon1600** [comment]
apparently that video no longer exists. I replaced that link with a new. In the future the youtube downloader should throw an exception or something to indicate that, but for now I made it to return an empty array to fix this undefined error:  
https://github.com/Athlon1600/youtube-downloader/commit/e064d4aed83300f4ed747bc3e98311dcae3ce4d6
