### ISSUE TITLE
How to go around age gate

### ISSUE THREAD

**Issue by cristalix** [Athlon1600/youtube-downloader#3]
You can download age-gated videos too.
```
// age-gate
if(strpos($html, 'player-age-gate-content') !== false){
	// nothing you can do folks...
	return false;
}
```
There are 2 type age-gated videos:

**1. Regular age-gate video** 

Download process looks like this:

1. Download Youtube https://www.youtube.com/watch?v=HtVdAasjOgU and find it's age-gated.
2. Download `sts` id from https://www.youtube.com/embed/HtVdAasjOgU (`sts` is 17184)
3. jsonDecode request to https://www.youtube.com/get_video_info?video_id=HtVdAasjOgU&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FHtVdAasjOgU&sts=17184 and find links in `url_encoded_fmt_stream_map`

**2. Age-gate video with encrypted signature**

Similar like in first case but you need decrypt signature after step 3.
Demo video: https://www.youtube.com/watch?v=6kLq3WMV1nU

**Comment by bateller** [comment]
@cristalix Any way around this when the video has embedding blocked?

**Comment by Athlon1600** [comment]
Not a moment, no. I would just look into how youtube-dl does it:  
https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/youtube.py

**Comment by mesbahulalam** [comment]
bateller, It's possible now maybe, worked for the ones I tested on.
`
		if(preg_match('/(ytplayer.config|blankSwfConfig) = {(.*?)};/', $page_content, $match)){
			$o = json_decode('{'.$match[1].'}');
			$html5player = 'https:/'.$o->assets->js;
			$sts = $o->sts;
		}`
I have only tried with the video ids known to me, I didn't even bother to search and test with other ids.

**Comment by hex-firebone** [comment]
Hello guys,

why don't you guys try this library

https://github.com/hex-firebone/YouTube-Downloader

**Comment by Athlon1600** [comment]
This has been fixed now:  
https://github.com/Athlon1600/youtube-downloader/commit/65d99ea7e347808df5ef9419a17a1ccc407e5b9e
