### ISSUE TITLE
access denied by google video

### ISSUE THREAD

**Issue by TIRTAGT** [Athlon1600/youtube-downloader#34]
I got 403 FORBIDDEN when accessing a copyright/protected youtube video  :(

You can try experimenting some videos in my website: 
this will run perfectly fine (no copyrighted):
[https://tirtagt.xyz/downloader/YTDL/index.php?id=bcsU1paVmMM](url)

but this will got the forbidden message (copyrighted videos) :
[https://tirtagt.xyz/downloader/YTDL/index.php?id=5HwEy5ue9nY](url)

Did someone got a solution????

**Comment by TIRTAGT** [comment]
copyright videos with other youtube downloader:
[https://api.unblockvideos.com/youtube_downloader?id=5HwEy5ue9nY&selector=mp4&redirect=true](url)

the same 403 forbidden error :(

**Comment by Athlon1600** [comment]
finally fixed!
