### ISSUE TITLE
Empty list of links

### ISSUE THREAD

**Issue by thiscodeworks** [Athlon1600/youtube-downloader#35]
Hey, I tried updated version but on some videos it return empty array of links. It's missing "url_encoded_fmt_stream_map" is there any way to fix this?

Thanks.

**Comment by Athlon1600** [comment]
I pushed a few changes since yesterday, so you might want to try the updated version to see if it works now.

You can try it out on:
https://unblockvideos.com/

"**US - East**" server. That's the one that's using the latest version of youtube-downloader

**Comment by mesbahulalam** [comment]
> Hey, I tried updated version but on some videos it return empty array of links. It's missing "url_encoded_fmt_stream_map" is there any way to fix this?
> 
> Thanks.

I experienced the same issue but a refresh fixes it.

**Comment by thiscodeworks** [comment]
@Athlon1600 I'm using latest version, when debugging problem in curl response it's missing 
 "url_encoded_fmt_stream_map" but on unblockvideos.com all videos working, weird.

**Comment by Athlon1600** [comment]
latest version doesn't even parse video links through "url_encoded_fmt_stream_map"

https://github.com/Athlon1600/youtube-downloader/blob/master/src/YouTubeDownloader.php

^ do CTRL + F for "url_encoded_fmt_stream_map"

It's no longer there.

Make sure it's really the latest version:
```shell
composer require athlon1600/youtube-downloader "^2.0"
```

**Comment by thiscodeworks** [comment]
My bad sorry. Now its working but return like 20 unknown formats.

**Comment by Athlon1600** [comment]
This has since been fixed. Update to latest version.

**Comment by msyadav88** [comment]
I tried to download video from your given link but getting nothing. https://location0718.unblockvideos.com/index.php?q=nqus1alrZpSn2qpgqafbqK3ElWaYos-RqZqkm5yl13GpsY62f4hsrHqtqg . Please guide.
![image](https://user-images.githubusercontent.com/14232868/98443037-d4f57380-212e-11eb-864c-fdd8eb280137.png)
