### ISSUE TITLE
Improve video info

### ISSUE THREAD

**Issue by mesbahulalam** [Athlon1600/youtube-downloader#36]
Will it be possible to update the `parseItagInfo()` using the mime parsing methods used in [this file](https://github.com/mesbahulalam/PHPYouTubeDownloader/blob/master/YouTubeDownloader.php) ?

**Comment by Athlon1600** [comment]
might be better to just get all that itag info right off of youtube-dl itself:  
https://github.com/ytdl-org/youtube-dl/blob/master/youtube_dl/extractor/youtube.py#L430

I already started on that here:
https://github.com/Athlon1600/youtube-downloader/commit/c8fce34d5b981234537d98fa904a5793a521c942

**Comment by Athlon1600** [comment]
No longer relevant. We are pulling all the itag info from youtube-dl now.
https://github.com/Athlon1600/youtube-downloader/blob/master/src/Parser.php
