### ISSUE TITLE
Everytime do a https

### ISSUE THREAD

**Issue by cristalix** [Athlon1600/youtube-downloader#4]
Change 

`$player_url = str_replace('//', 'http://', $matches[1]);`

to

`$player_url = str_replace('//', 'https://', $matches[1]);`

**Comment by cristalix** [comment]
https://blog.codinghorror.com/lets-encrypt-everything/ - why to use https everywhere possible. Blog post from Stackoverflow founder.

**Comment by Athlon1600** [comment]
Fixed:
https://github.com/Athlon1600/youtube-downloader/commit/33a87a91a07484de1ccf1460de33fecbfa6e3bd9
