### ISSUE TITLE
composer.lock Missing composer.json uses ‘require’

### ISSUE THREAD

**Issue by real-cereal-boy** [Athlon1600/youtube-downloader#40]

**Comment by kinglyl** [comment]
I recommend you to use Alltube as a libarary to get video url (not only youtube)

**Comment by Athlon1600** [comment]
> composer.lock Missing composer.json uses ‘require’

I need to know more than that. If this is to do with heroku, then you should know that I'll be making this fully heroku-deployable real soon. Also, alltube doesn't work at the moment either.
