### ISSUE TITLE
Vevo videos not working

### ISSUE THREAD

**Issue by babynew** [Athlon1600/youtube-downloader#41]
Vevo video download not working.Any one facing?

**Comment by Athlon1600** [comment]
you need to upgrade to latest version - v2.0.3. Once I did that for one of my proxy sites, youtube started working for me again:
![image](https://user-images.githubusercontent.com/1063088/73804906-ca1a4680-478a-11ea-9103-646f00e2f59b.png)
 
https://unblockvideos.com/

US-EAST server works just fine.
