### ISSUE TITLE
How to get best quality mp4 with audio and video

### ISSUE THREAD

**Issue by ndsda** [Athlon1600/youtube-downloader#42]
I'm looking for videos with format "mp4, 1080p, video/audio" or "mp4, 720p, video/audio".

But the links returned for the videos I've tried (movie trailers) mostly have a format that's either video or audio or unknown.

Is there a way to download the best quality mp4 version available with video and audio?

All the videos I've tried have 1080p streams with sound on youtube.com

**Comment by kinglyl** [comment]
recommend Alltube video download library. It can fix this problem

**Comment by mesbahulalam** [comment]
> All the videos I've tried have 1080p streams with sound on youtube.com
The thing is YouTube serves videos with quality higher than 640x480p as separate streams of audio and video and the YouTube player plays them asynchronously so we can see them as whole. So, you cannot download them directly from YouTube as a single file containing both audio and video streams. You have to use either ffmpeg or some other media file muxer to get a complete file.

**Comment by ndsda** [comment]
> The thing is YouTube serves videos with quality higher than 640x480p as separate streams of audio and video and the YouTube player plays them asynchronously so we can see them as whole.

Ah right, I didn't know that, thanks for the info.

> You have to use either ffmpeg or some other media file muxer to get a complete file.

Thanks for this suggestion. I was able to use FFmpeg to add the audio to the video and save as a mp4.
