### ISSUE TITLE
Empty array

### ISSUE THREAD

**Issue by sam9177** [Athlon1600/youtube-downloader#43]
Hello,
My steps with clear Debian 10
apt update && apt -y upgrade
apt -y install php php-common
apt -y install php-cli php-fpm php-json php-pdo php-mysql php-zip php-gd  php-mbstring php-curl php-xml php-pear php-bcmath
apt -y install libapache2-mod-php
systemctl restart apache2
apt install curl php-cli php-mbstring git unzip
cd ~
curl -sS https://getcomposer.org/installer -o composer-setup.php
php composer-setup.php --install-dir=/usr/local/bin --filename=composer
cd /var/www/html
composer require athlon1600/youtube-downloader

(/var/www/html/youtube.php):

require  'var/www/html/vendor/autoload.php';
use YouTube\YouTubeDownloader;
$yt = new YouTubeDownloader();
$links = $yt->getDownloadLinks("https://www.youtube.com/watch?v=QxsmWxxouIM");
var_dump($links);

And it's show array(0) { }

What did I do wrong?

**Comment by Athlon1600** [comment]
youtube made some changes, so you're probably using an oudated version of youtube-downloader.  
  
v2.0.3 was released just 5 days ago:  
https://github.com/Athlon1600/youtube-downloader/releases/tag/v2.0.3

**Comment by sam9177** [comment]
I use this version.
Please, can you help me?

**Comment by sam9177** [comment]
I use this version.
Please, can you help me?

**Comment by Athlon1600** [comment]
okay, YouTubeDownloader class has an additional method you can use to debug this:  
> getLastError()
  
what do you get when you do this:  
`var_dump($yt->getLastError());`
  
right after `getDownloadLinks`

**Comment by sam9177** [comment]
NULL array(0) { }

I can give you root access to VPS. Maybe this would be better?
How can I privately give it to you?

**Comment by Athlon1600** [comment]
> NULL array(0) { }

are you calling `getLastError` before `getDownloadLinks` or after? Because it should be after

> https://www.youtube.com/watch?v=QxsmWxxouIM

If I put this video into this demo app (that runs latest youtube-downloader version) than it all works.

**Comment by sam9177** [comment]
require 'var/www/html/vendor/autoload.php';
use YouTube\YouTubeDownloader;
$yt = new YouTubeDownloader();
$links = $yt->getDownloadLinks("https://www.youtube.com/watch?v=QxsmWxxouIM");
var_dump($yt->getLastError());
var_dump($links);


As I said I can give you root.

**Comment by sam9177** [comment]
Maybe I didn’t install any package?

**Comment by PhamMinhKha** [comment]
on localhost work perfect and i upload to vps and get same error

**Comment by PhamMinhKha** [comment]
i found reason. i have https but i send http request

**Comment by sam9177** [comment]
> i found reason. i have https but i send http request

What I shoud fix?

**Comment by PhamMinhKha** [comment]
> > i found reason. i have https but i send http request
> 
> What I should fix?

just add https before url

> http://domain.com/api/youtube/id --> https://domain.com/api/youtube/id

detail https://imgur.com/96OBdZn
