### ISSUE TITLE
problem when using it on local server XAMPP

### ISSUE THREAD

**Issue by TIRTAGT** [Athlon1600/youtube-downloader#46]
Because it doesn't tell where i should to get started, i searched on all folders and find index.html on public folder's.

I was quite happy when i load the index.html on my web browser, because it looks the same as the DEMO URL : https://youtube-downloader3.herokuapp.com/

But, when i'm pasting the YouTube links on the text button provided and pressing fetch.

This bad errors pops up : `PHP Warning:  require(../vendor/autoload.php): failed to open stream: No such file or directory in htdocs\Athlon\public\video_info.php on line 3.

PHP Fatal error:  require(): Failed opening required '../vendor/autoload.php'

So i was guessing ah i need to find those autoload.php thingies, but cant find any where on the zip that i downloaded from here :/ tried searching on all src/,tests/,public/ but No luck.

![Screenshot_680](https://user-images.githubusercontent.com/55649705/78153761-a0695d00-7465-11ea-9978-eec89e6d7deb.png)

**Comment by Athlon1600** [comment]
^ inside that directory, you need to open up the command line and run `composer install`.
And that will create a "vendor" directory.

![](https://i.imgur.com/sDJdj4h.png?1)

**Comment by TIRTAGT** [comment]
Ah i cant install composer because its not supported on my machine right now :(
But i already find a way to run your code by moving any of the files in a folder and let it work itself.
