### ISSUE TITLE
Not working since couple month ago

### ISSUE THREAD

**Issue by ArmanEsf** [Athlon1600/youtube-downloader#49]
hey Athlon1600,
i'm using your lib for a Telegram bot and i just realized that.
and now as i'm testing it and for making sure using your example
i mean this :
`use YouTube\YouTubeDownloader;`

`$yt = new YouTubeDownloader();`

`$links = $yt->getDownloadLinks("https://www.youtube.com/watch?v=LJzCYSdrHMI");`

`var_dump($links);`
it returns an empty array : 
`array(0) { }`

Thanks in advance. 👍

**Comment by Athlon1600** [comment]
empty array can sometimes mean an error:
https://github.com/Athlon1600/youtube-downloader/blob/master/src/YouTubeDownloader.php#L205

what happens when you call this right after:
```php
var_dump($yt->getLastError());
```

? It's possible that youtube has blocked your IP temporarily and that would show up as 429 error

**Comment by ArmanEsf** [comment]
tnQ for your response,
but i did that an returns nothing! :
`Output of var_dump($links) :`
`array(0) { }`
`Output of getLastError() :`
and i'm sure youtube didn't blocked my IP because i tested it.

any other idea?

**Comment by Athlon1600** [comment]
are you sure you're using the latest version of youtube-downloader? Do a `composer update`. It just tested your piece of code from my end, and it returns all the links just fine...

**Comment by ArmanEsf** [comment]
it's probably that, because that day i checked the commits and didn't sound like update!
and since i'm using on a shared host there's no composer! and i required your project files manually, now i should some how update those, since you add some new features i couldn't use it yet!

after all Thanks you it was this.
