### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by inglesuniversal** [Athlon1600/youtube-downloader#53]
Awesome script...

Is there a way to fetch the title of the video and give an option of:

save as: 'source video title.mp4'

can the script handle downloads in mp3 out of the box?

**Comment by Athlon1600** [comment]
> Is there a way to fetch the title of the video and give an option of:

not yet. I'll add it to my to-do list.

> can the script handle downloads in mp3 out of the box?

nope. You would have to download whatever format youtube is giving you, and then run ffmpeg through that file to convert it to .mp3 or whatever other format you want.
