### ISSUE TITLE
How to use proxy to hide my server's original ip

### ISSUE THREAD

**Issue by azinkey** [Athlon1600/youtube-downloader#56]
I saw at (savefrom . net) using same thing but every time on request there IP have changed e.g.

https://r4---sn-aigzrn7s.googlevideo.com/videoplayback?expire=1590056078&ei=LgDGXp-eK-y1xN8P1pmwsAY&ip=**5.180.220.89**

what kind of technologies they are using ?

this script is no longer work in production environment due to error 421 to many request so can we use proxy to hide server's original ip from blocked

**Comment by kinglyl** [comment]
My server is blocked too
429 Too many requests

**Comment by azinkey** [comment]
Moved to youtube-dl as it support better proxy then curl :(

**Comment by Athlon1600** [comment]
Would this work for you?

```php
use YouTube\YouTubeDownloader;

$yt = new YouTubeDownloader();

$yt->getBrowser()->setProxy('ip:port');

$links = $yt->getDownloadLinks("https://www.youtube.com/watch?v=LJzCYSdrHMI");

var_dump($links);
```

**Comment by LegionerJ** [comment]
Dear Athlon1600 ,Your library has not been updated on composer  and gives "calling undefined setProxy function error".

**Comment by Athlon1600** [comment]
Do `composer update` now. The new v2.0.8 now includes setProxy method:  
https://github.com/Athlon1600/youtube-downloader/releases

**Comment by w3lifer** [comment]
@Athlon1600 
And how I can to specify the username and password for the proxy?
