### ISSUE TITLE
Empty links list

### ISSUE THREAD

**Issue by krychu90** [Athlon1600/youtube-downloader#57]
Hello,
sometimes method _getDownloadLinks()_ returns empty list, for example for this video:
https://www.youtube.com/watch?v=dQw4w9WgXcQ

Regards.

**Comment by rustynail1984** [comment]
Thats because YouTube changes for the most Videos the Signature Cipher.

find in YouTubeDownload.php line 138

`$cipher = isset($item['cipher']) ? $item['cipher'] : '';`

change it to

```
if(isset($item['cipher']) || isset($item['signatureCipher']))
{
    $cipher = ($item['signatureCipher']) ? $item['signatureCipher'] : $item['cipher'];
}
```

**Comment by Athlon1600** [comment]
Fixed in this release:
https://github.com/Athlon1600/youtube-downloader/releases/tag/v2.0.7

Thanks to rusty nail
