### ISSUE TITLE
Random errors

### ISSUE THREAD

**Issue by GeorgeHulpoi** [Athlon1600/youtube-downloader#59]
Hello! I get these errors sometimes when I use the library

`<br />
<b>Notice</b>:  Trying to access array offset on value of type null in <b>C:\XAMPP\htdocs\vendor\athlon1600\youtube-downloader\src\YouTubeDownloader.php</b> on line <b>119</b><br />
<br />
<b>Notice</b>:  Trying to access array offset on value of type null in <b>C:\XAMPP\htdocs\vendor\athlon1600\youtube-downloader\src\YouTubeDownloader.php</b> on line <b>119</b><br />
<br />
<b>Notice</b>:  Trying to access array offset on value of type null in <b>C:\XAMPP\htdocs\vendor\athlon1600\youtube-downloader\src\YouTubeDownloader.php</b> on line <b>120</b><br />
<br />
<b>Notice</b>:  Trying to access array offset on value of type null in <b>C:\XAMPP\htdocs\vendor\athlon1600\youtube-downloader\src\YouTubeDownloader.php</b> on line <b>120</b><br />`

composer.json:
`{
    "require": {
        "athlon1600/youtube-downloader": "^2.0",
        "php-ffmpeg/php-ffmpeg": "^0.16.0"
    }
}`

I don't know how to reproduce the problem, sometimes happens with the data that usually work.

**Comment by Athlon1600** [comment]
This should be fixed by now:  
https://github.com/Athlon1600/youtube-downloader/commit/68d5947678a2ff93753dcde9a152ee551f5f340c

update your youtube-downloader package.
