### ISSUE TITLE
Error 403 on all Encrypted Videos

### ISSUE THREAD

**Issue by rustynail1984** [Athlon1600/youtube-downloader#67]
Since today i get on the most Encrypted Videos a **403 Error** if i try to download, and yes i use the same IP as i scrape the URLs from YouTube. _I think it is a Signature issue._

Example Video: https://www.youtube.com/watch?v=2vjPBrBU-TM

**Comment by Athlon1600** [comment]
Yup. It was a signature issue. Fixed in a new release:
https://github.com/Athlon1600/youtube-downloader/releases/tag/v2.0.9

just do `composer update` now.
