### ISSUE TITLE
Not up-to-date (28 july 2020)

### ISSUE THREAD

**Issue by AgentSmith0** [Athlon1600/youtube-downloader#68]
The youtube downloader scripts needs to be updated. It is not working anymore.

**Comment by Athlon1600** [comment]
Do `composer update`. I just pushed through a new fixed version:  
https://github.com/Athlon1600/youtube-downloader/releases

**Comment by Ez001** [comment]
Hi Athlon1600, great work you have done so far....It seems I can get to download videos in HD.

**Comment by Athlon1600** [comment]
> It seems I can't get to download videos in HD.

I need more details than that. And this probably belongs as a separate issue now
