### ISSUE TITLE
Change youtube-dl extractor

### ISSUE THREAD

**Issue by FabioZangirolami** [Athlon1600/youtube-downloader#70]
Hello very useful your project. But I want to change the url for a video from other domains, cnn, cnbc, foxnews. The youtube-dl git project has the [https://github.com/ytdl-org/youtube-dl/tree/master/youtube_dl/extractor](https://github.com/ytdl-org/youtube-dl/tree/master/youtube_dl/extractor). How can I take advantage of your the code and do this? Thank you.

**Comment by Athlon1600** [comment]
You want to use this youtube-downloader to be able to download videos from sites other than youtube.com? That's not really the purpose of this project and it would involve massive work

**Comment by kinglyl** [comment]
recommend https://github.com/rudloff/alltube
