### ISSUE TITLE
No video found!

### ISSUE THREAD

**Issue by loistloh** [Athlon1600/youtube-downloader#76]
May be the Youtube update the algorithm，now "No video found!"

**Comment by alexlarocca** [comment]
Confirmed. The function getDownloadLinks returns always an empty array

**Comment by ndsda** [comment]
Yes, I have the same problem for a few weeks. I copied the latest code but experience the same issue.

**Comment by Athlon1600** [comment]
Fixed in v2.1.1:  
https://github.com/Athlon1600/youtube-downloader/releases
