### ISSUE TITLE
Not available for limited videos?

### ISSUE THREAD

**Issue by kendai912** [Athlon1600/youtube-downloader#77]
With limited videos, the script returns a download URL but it gives HTTP ERROR 404 when I open the URL.

For example, this is the limited video I uploaded on YouTube: https://www.youtube.com/watch?v=n80CYo5L8mQ.

This project is not available for limited videos? Or how can I resolve it?

**Comment by kendai912** [comment]
It was just my misunderstanding, my bad.

**Comment by fabienlege** [comment]
I have the same problem.
@kendai912 How have you solved this problem ?
