### ISSUE TITLE
Some URL returned by getDownloadLinks not working (404)

### ISSUE THREAD

**Issue by fabienlege** [Athlon1600/youtube-downloader#78]
In some random case, URLs returned by getDownloadLinks return 404 when open. why and how to solve this problem ?
![image](https://user-images.githubusercontent.com/2045814/96694331-a0d92f00-1388-11eb-858c-b1f4e755265d.png)
thank's

**Comment by Athlon1600** [comment]
what youtube video is this for? 404 error tells me that you might have wrongly pasted that link into your browser.

**Comment by rajatvermaiam** [comment]
https://www.youtube.com/watch?v=kffacxfA7G4
woking fine on your server but error in actual is there any diff between repo and ur demo site?
