### ISSUE TITLE
Use only free content as examples in documentation and elsewhere.

### ISSUE THREAD

**Issue by jdebp** [Athlon1600/youtube-downloader#81]
Given the events of yesterday with youtube-dl, it is very unwise to be using non-free Blur songs as example usages of the tool. Please immediately replace all doco and screenshots, and any commentary in the code itself, with examples that download content that is not restrictively copyright licensed.

* https://github.com/github/dmca/blob/master/2020/10/2020-10-23-RIAA.md

* https://news.ycombinator.com/item?id=24873742

**Comment by Athlon1600** [comment]
yes, definitely needed to make some changes given recent events. Added a legal disclaimer too:  
https://github.com/Athlon1600/youtube-downloader#warning-legal-disclaimer  
  
which is something that `youtube-dl` did not previously have. Hopefully we're going to be okay.
