### ISSUE TITLE
Some Videos returning 403 forbidden error

### ISSUE THREAD

**Issue by cclegend90** [Athlon1600/youtube-downloader#84]
Also IP is same for fetching URLs and for streaming videos, because I'm on localhost.

However it works on your demo site https://youtube-downloader3.herokuapp.com:

Video I'm trying to download: https://www.youtube.com/watch?v=kffacxfA7G4

**Comment by rajatvermaiam** [comment]
yeah same issue with these type of video...but working fine on your demo site.. how?

**Comment by rajatvermaiam** [comment]
yeah same error on when fetching with different ip and giving link to someone.. is there any fix?
