### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by azeekhan1** [Athlon1600/youtube-downloader#9]
Hello, i just wanted to know if you can help me install that on my server, i have treid everything installing but it just wont show. can you please please tell me how i can install that on my vps. i have centos 6

**Comment by Athlon1600** [comment]
I need to know where are you having problems during installation. Do you have composer installed on your server? What happens when you run this in your command line:  
```
composer require athlon1600/youtube-downloader
```

**Comment by azeekhan1** [comment]
hello, when i run the command, it has three files, composer.lock, composer.json and vendor but when i goto my domain name and use nothing show up.

**Comment by Athlon1600** [comment]
Right, you just need to create an index.php file right next to that /vendor/ directory with this code:  
```php
require('/vendor/autoload.php');
$yt = new YouTubeDownloader();
$links = $yt->getDownloadLinks("https://www.youtube.com/watch?v=QxsmWxxouIM");

var_dump($links);
```

**Comment by azeekhan1** [comment]
Thank you so much for replying, i added index.php and added the code you provide now when i goto my domain index page it shows 

> $yt = new YouTubeDownloader(); $links = $yt->getDownloadLinks("https://www.youtube.com/watch?v=QxsmWxxouIM"); var_dump($links);

**Comment by Athlon1600** [comment]
?? Did you forget to surround that code with  
```php
<?php

...

?>
```

**Comment by hex-firebone** [comment]
Hello guys,

why don't you guys try this library

https://github.com/hex-firebone/YouTube-Downloader

**Comment by Athlon1600** [comment]
that's just a rip of this script...
