### ISSUE TITLE
Performance: use gzip and embed url

### ISSUE THREAD

**Issue by ewwink** [Athlon1600/youtube-downloader#91]
using request header `gzip` we can save up to 500% and using gzip + embed up to 3500%, I know some video cannot be embedded and maybe we can use failover to normal URL

```php
    public function get($url)
    {
        $ch = curl_init($url);

        # add this line
        curl_setopt($ch, CURLOPT_ENCODING, 'gzip'); 
```

![ytdl](https://user-images.githubusercontent.com/760764/102977710-f58a5900-4535-11eb-9c22-70d87ecfbe9e.jpg)

**Comment by AgentSmith0** [comment]
Hello, this is a nice idea. Maybe you create a pull request?

**Comment by Athlon1600** [comment]
every HTTP request made from this library, already asks to return gzip by default. See source:
https://github.com/Athlon1600/php-curl-client/blob/master/src/BrowserClient.php#L10
