### ISSUE TITLE
Code not properly functioning

### ISSUE THREAD

**Issue by Joshii01** [Athlon1600/youtube-downloader#98]
Hello there @Athlon1600 i tried inserting this code into my website but when i insert a video link to test it it wont show the video, please help me fix this issue, thanks!
![image](https://user-images.githubusercontent.com/78946868/108758837-6b904980-7500-11eb-8fe5-3165f96380cf.png)

**Comment by Athlon1600** [comment]
need more information, like a link to your site or what the console on your browser's developer tools show
