### ISSUE TITLE
403 Error for Encrypted Videos

### ISSUE THREAD

**Issue by rustynail1984** [Athlon1600/youtube-downloader#99]
Hi there,

i think the Signature Decoder is broken, i got on all Encrypted Videos 403 error.

Example Video: https://www.youtube.com/watch?v=2vjPBrBU-TM

**Comment by 5wcx** [comment]
me too

**Comment by 5wcx** [comment]
https://youtu.be/72oON3ChgPc

**Comment by Athlon1600** [comment]
both of those videos load just fine for me?
https://youtube-downloader-version2.herokuapp.com/

are you sure you're using the latest version AND trying to view that video from the same IP address?

**Comment by rustynail1984** [comment]
Hi.
of course i used the same ip and the latest version.

Now 4 days are over and YouTube has changed the signature algorithm again. I made screenshots of the relevant functions of the base.js. from 4 days ago and today.

4 days ago
![23-02-2020](https://user-images.githubusercontent.com/65692019/109378000-761b5c00-78cf-11eb-943d-067e053e4a61.png)
![23-02-2020-2](https://user-images.githubusercontent.com/65692019/109378003-79164c80-78cf-11eb-98b3-9b23018b6ff5.png)

Today
![27-02-2020](https://user-images.githubusercontent.com/65692019/109378004-7ae01000-78cf-11eb-8830-4a87dbaa8f3f.png)
![27-02-2020-2](https://user-images.githubusercontent.com/65692019/109378009-7ca9d380-78cf-11eb-9283-3ac6dd78c5c4.png)


This is the fix: update RegEx in line 70 of SignatureDecoder.php

// extract all relevant statements within that block
// wm.vY(a,1);
if (preg_match_all('/([a-z0-9$]{2})(\.|(\[["\']))([a-z0-9]{2})(["\']\])?\([^,]+,(\d+)\)/i', $jsCode, $matches) != false)

**Comment by Athlon1600** [comment]
^ right, that would probably work. But the JS player I get back from every video is this:
https://www.youtube.com/s/player/4fe52f49/player_ias.vflset/en_US/base.js

and the code on that looks like this:
![](https://i.imgur.com/xUgM68L.png)

no function names in quotes. Can you link me to the player that has that code you're showing?

**Comment by rustynail1984** [comment]
Hi,

this was the base,js: https://www.youtube.com/s/player/4fe52f49/player_ias.vflset/de_DE/base.js

As i already said, YouTube changed Sig Algo again and this "do" function is currently not existing anymore in base.js
But this is the reason why it didnt workig at this day (6 days ago).  I fixed it at the same day and it was working again.

Maybe you should just change the regex, which serves as a failure protection, in case there is a Sig Algo function in quotes again in the future.

**Comment by Athlon1600** [comment]
> Maybe you should just change the regex, which serves as a failure protection, in case there is a Sig Algo function in quotes again in the future.

no harm in that. Done:  
https://github.com/Athlon1600/youtube-downloader/releases/tag/v2.1.2
